# Generated by Django 5.1.4 on 2025-01-12 06:12

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", creditcards.models.CardNumberField(max_length=25)),
                ("expired_date", models.DateTimeField()),
                ("card_holder_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expired_date", models.DateTimeField()),
                ("cost_amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("1 oylik", "ONE_MONTH"),
                            ("3 oylik", "THREE_MONTHS"),
                            ("6 oylik", "SIX_MONTHS"),
                            ("1 yillik", "ONE_YEAR"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscribe",
                "verbose_name_plural": "Subscribes",
            },
        ),
    ]
